name       : mate-calc
version    : 1.20.3
release    : 6
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-calc-1.20.3.tar.xz : aae461f5c30048ea0eabdaada8b0e7ed9b9501076e9f16613363e79198c0605b
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Calculator tool for the MATE desktop
description: |
    This is `mate-calc`, a fork of `gnome-calc`, the calculator application
    that was previously in the OpenWindows Deskset of the Solaris 8
    operating system.

    It incorporates a multiple precision arithmetic packages based on the
    work of Professor Richard Brent, who has also kindly given me
    permission to make it available.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
