name       : mate-calc
version    : 1.22.0
release    : 7
source     :
    - https://github.com/mate-desktop//mate-calc/archive/v1.22.0.tar.gz : 75678a6f7120933dbef2352213a809d8d443e8c5360cf0f3697a8efb9f014ab4
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Calculator tool for the MATE desktop
description: |
    This is `mate-calc`, a fork of `gnome-calc`, the calculator application
    that was previously in the OpenWindows Deskset of the Solaris 8
    operating system.

    It incorporates a multiple precision arithmetic packages based on the
    work of Professor Richard Brent, who has also kindly given me
    permission to make it available.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
    - mate-common
    - yelp-tools
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
