name       : mate-calc
version    : 1.20.1
release    : 4
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-calc-1.20.1.tar.xz : 0761c2fff146d9976d586f21598d1ea39812171de3e0f02edb9435a2e2306002
license    : GPL-2.0-only
component  : desktop.mate
summary    : Calculator tool for the MATE desktop
description: |
    This is `mate-calc`, a fork of `gnome-calc`, the calculator application
    that was previously in the OpenWindows Deskset of the Solaris 8
    operating system.

    It incorporates a multiple precision arithmetic packages based on the
    work of Professor Richard Brent, who has also kindly given me
    permission to make it available.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
