name       : mate-calc
version    : 1.24.1
release    : 11
source     :
    - https://github.com/mate-desktop/mate-calc/releases/download/v1.24.1/mate-calc-1.24.1.tar.xz : 5c2d1b0101c087c3fdae143058994a76093590693a33392bc2329756708dad46
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Calculator tool for the MATE desktop
description: |
    This is `mate-calc`, a fork of `gnome-calc`, the calculator application that was previously in the OpenWindows Deskset of the Solaris 8 operating system.

    It incorporates a multiple precision arithmetic packages based on the work of Professor Richard Brent, who has also kindly given me permission to make it available.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
