name       : mate-calc
version    : 1.24.2
release    : 12
source     :
    - https://github.com/mate-desktop/mate-calc/releases/download/v1.24.2/mate-calc-1.24.2.tar.xz : d4a4c8ff51c4611b32a129b7cad33c3bb8a1ec6b9d5f209aa4ee0c8f1b90e8f9
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Calculator tool for the MATE desktop
description: |
    This is `mate-calc`, a fork of `gnome-calc`, the calculator application that was previously in the OpenWindows Deskset of the Solaris 8 operating system.

    It incorporates a multiple precision arithmetic packages based on the work of Professor Richard Brent, who has also kindly given me permission to make it available.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
